//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Scheduler  : IComparable<Scheduler>
    {
        [Key]
        public int id { get; set; }
        [Required]
        [Display(Name = "Name")]
        [MaxLength(50)]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        [MaxLength(2000)]
        [Display(Name = "Description")]
        public string description { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Time")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime EndDate { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Add On")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime AddOn { get; set; } = DateTime.Now;
        public int userId { get; set; }
    
        public virtual Account Account { get; set; }

        public int CompareTo(Scheduler other)
        {
            return DateTime.Compare(this.EndDate,other.EndDate);
        }

    }
}
